routes/web.php
<?php 

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth']], function() {

Route::get('/', 'PagesController@index');
Route::get('/project', 'PagesController@projects');
Route::get('/tasks', 'PagesController@tasks');
Route::get('/system-page', 'PagesController@system');
Route::get('/proj-config', 'PagesController@projectconfiguration');
Route::get('/add-procurement', 'PagesController@addprocurement');
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::get('/my-profile', 'UserController@profile');
Route::get('/my-profile/{user}',  ['as' => 'users.edit', 'uses' => 'UserController@edit']);
Route::patch('/my-profile/{user}/update',  ['as' => 'users.update', 'uses' => 'UserController@update']);
Route::post('/my-profile', 'UserController@update_avatar');

/* Sytem Config Routes */
Route::group(['middleware' => 'is.admin'], function () {
Route::post('/system', ['as' => 'system.users.store', 'uses' => 'SystemController@store_users']);
Route::get('/system', ['as' => 'system.users.index', 'uses' => 'SystemController@index_users']);
Route::get('/system/users/create', ['as' => 'system.users.create', 'uses' => 'SystemController@create_users']);
Route::delete('/system/users/{user} ', ['as' => 'system.users.destroy', 'uses' => 'SystemController@destroy_users']);
Route::patch('/system/users/{user}', ['as' => 'system.users.update', 'uses' => 'SystemController@update_users']);
Route::get('/system/users/{user}/edit', ['as' => 'system.users.edit', 'uses' => 'SystemController@edit_users']);
});

/* Projects and Tasks Routes */
Route::model('tasks', 'Task');
Route::model('procurements', 'Procurement');
Route::model('elements', 'Element');
Route::model('locations', 'Location');
Route::model('projects', 'Project');

Route::bind('task', function($value, $route) {
	return App\Task::whereSlug($value)->first();
});
Route::bind('project', function($value, $route) {
	return App\Project::whereSlug($value)->first();
});
Route::resource('projects.procurements', 'ProcurementsController');
Route::resource('projects.locations', 'LocationsController');
Route::resource('projects.elements', 'ElementsController');
Route::resource('/projects', 'ProjectsController');
Route::resource('procurements.tasks', 'TasksController');



});


Auth::routes();

app/Project.php
<?php

namespace App;

use App\Element;
use App\Task;
use App\Location;
use App\Procurement;
use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
	protected $table = 'projects';

	protected $guarded = [];

	public function elements()
	{
		return $this->hasMany(Element::class, 'project_id' , 'id');
	}
	public function tasks()
	{
		return $this->hasMany(Task::class);
	}
	public function locations()
	{
		return $this->hasMany(Location::class, 'project_id' , 'id');
	}
}

app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Procurement;
use App\Element;
use App\Project;
use App\Task;
use App\Location;
use Illuminate\Support\Facades\Input;
use Redirect;

class ProjectsController extends Controller
{
    public function index()
	{
		$projects = Project::all();
		return view('projects.index', compact('projects'));
	}

	public function create()
	{
		return view('projects.create');
	}

	public function store()
	{
		$input = Input::all();
		Project::create( $input );
 
		return Redirect::route('projects.index')->with('message', 'Project created');	}

	public function show(Project $project)
	{
		$projects = Project::all();
		return view('projects.show', compact('project','projects'));
	}

	public function edit(Project $project)
	{
		return view('projects.edit', compact('project'));
	}

	public function update(Project $project)
	{
		$input = array_except(Input::all(), '_method');
		$project->update($input);
 
		return Redirect::route('projects.show', $project->slug)->with('message', 'Project updated.');	}

	public function destroy(Project $project)
	{
		$project->delete();
 
		return Redirect::route('projects.index')->with('message', 'Project deleted.');
	}
}

resources/views/projects/create.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Create Project</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('projects.store') }}">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                                @if ($errors->has('firstname'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('slug') ? ' has-error' : '' }}">
                            <label for="slug" class="col-md-4 control-label">Slug</label>

                            <div class="col-md-6">
                                <input id="slug" type="text" class="form-control" name="slug" value="{{ old('slug') }}" required autofocus>

                                @if ($errors->has('slug'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('slug') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('project_manager') ? ' has-error' : '' }}">
                            <label for="project_manager" class="col-md-4 control-label">Project Manager</label>

                            <div class="col-md-6">
                                <input id="project_manager" type="text" class="form-control" name="project_manager" value="{{ old('project_manager') }}" required autofocus>

                                @if ($errors->has('project_manager'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('project_manager') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('address1') ? ' has-error' : '' }}">
                            <label for="address1" class="col-md-4 control-label">Address 1</label>

                            <div class="col-md-6">
                                <input id="address1" type="text" class="form-control" name="address1" value="{{ old('address1') }}" required>

                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('address1') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        
                        <div class="form-group{{ $errors->has('address2') ? ' has-error' : '' }}">
                            <label for="address2" class="col-md-4 control-label">Address 2</label>

                            <div class="col-md-6">
                                <input id="address2" type="text" class="form-control" name="address2" value="{{ old('address2') }}" required autofocus>

                                @if ($errors->has('address2'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('address2') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('postcode') ? ' has-error' : '' }}">
                            <label for="postcode" class="col-md-4 control-label">Post Code</label>

                            <div class="col-md-6">
                                <input id="postcode" type="text" class="form-control" name="postcode" value="{{ old('postcode') }}" required autofocus>

                                @if ($errors->has('postcode'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('postcode') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('state') ? ' has-error' : '' }}">
                            <label for="state" class="col-md-4 control-label">State</label>

                            <div class="col-md-6">
                                <input id="state" type="text" class="form-control" name="state" value="{{ old('state') }}" required autofocus>

                                @if ($errors->has('state'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('state') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('country') ? ' has-error' : '' }}">
                            <label for="country" class="col-md-4 control-label">Country</label>

                            <div class="col-md-6">
                                <input id="country" type="text" class="form-control" name="country" value="{{ old('country') }}" required autofocus>

                                @if ($errors->has('country'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('country') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

						<div class="form-group{{ $errors->has('start_date') ? ' has-error' : '' }}">
                            <label for="start_date" class="col-md-4 control-label">Start Date</label>

                            <div class="col-md-6">
                                <input id="start_date" type="date" class="form-control" name="start_date" value="{{ old('start_date') }}" autofocus>

                                @if ($errors->has('start_date'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('start_date') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

						<div class="form-group{{ $errors->has('original_estimate') ? ' has-error' : '' }}">
                            <label for="original_estimate" class="col-md-4 control-label">Original Estimate</label>

                            <div class="col-md-6">
                                <input id="original_estimate" type="date" class="form-control" name="original_estimate" value="{{ old('original_estimate') }}" autofocus>

                                @if ($errors->has('original_estimate'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('original_estimate') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

						<div class="form-group{{ $errors->has('current_estimate') ? ' has-error' : '' }}">
                            <label for="current_estimate" class="col-md-4 control-label">Current Estimate</label>

                            <div class="col-md-6">
                                <input id="current_estimate" type="date" class="form-control" name="current_estimate" value="{{ old('current_estimate') }}" autofocus>

                                @if ($errors->has('current_estimate'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('current_estimate') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

						<div class="form-group{{ $errors->has('status') ? ' has-error' : '' }}">
                            <label for="status" class="col-md-4 control-label">Status</label>

                            <div class="col-md-6">
                                <input id="status" type="text" class="form-control" name="status" value="{{ old('status') }}" autofocus>

                                @if ($errors->has('status'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('status') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Create Project
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/projects/edit.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Edit Project</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('projects.update', $project->slug) }}">
                        {{ csrf_field() }}
                        {{ method_field('patch') }}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ $project->name }}"  autofocus>

                                @if ($errors->has('firstname'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('slug') ? ' has-error' : '' }}">
                            <label for="slug" class="col-md-4 control-label">Slug</label>

                            <div class="col-md-6">
                                <input id="slug" type="text" class="form-control" name="slug" value="{{ $project->slug }}"  autofocus>

                                @if ($errors->has('slug'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('slug') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('project_manager') ? ' has-error' : '' }}">
                            <label for="project_manager" class="col-md-4 control-label">Project Manager</label>

                            <div class="col-md-6">
                                <input id="project_manager" type="text" class="form-control" name="project_manager" value="{{ $project->project_manager }}"  autofocus>

                                @if ($errors->has('project_manager'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('project_manager') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('address1') ? ' has-error' : '' }}">
                            <label for="address1" class="col-md-4 control-label">Address 1</label>

                            <div class="col-md-6">
                                <input id="address1" type="text" class="form-control" name="address1" value="{{ $project->address1 }}" >

                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('address1') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        
                        <div class="form-group{{ $errors->has('address2') ? ' has-error' : '' }}">
                            <label for="address2" class="col-md-4 control-label">Address 2</label>

                            <div class="col-md-6">
                                <input id="address2" type="text" class="form-control" name="address2" value="{{ $project->address2 }}" autofocus>

                                @if ($errors->has('address2'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('address2') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('postcode') ? ' has-error' : '' }}">
                            <label for="postcode" class="col-md-4 control-label">Post Code</label>

                            <div class="col-md-6">
                                <input id="postcode" type="text" class="form-control" name="postcode" value="{{ $project->postcode }}" autofocus>

                                @if ($errors->has('postcode'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('postcode') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('state') ? ' has-error' : '' }}">
                            <label for="state" class="col-md-4 control-label">State</label>

                            <div class="col-md-6">
                                <input id="state" type="text" class="form-control" name="state" value="{{ $project->state }}"  autofocus>

                                @if ($errors->has('state'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('state') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('country') ? ' has-error' : '' }}">
                            <label for="country" class="col-md-4 control-label">Country</label>

                            <div class="col-md-6">
                                <input id="country" type="text" class="form-control" name="country" value="{{ $project->country }}" autofocus>

                                @if ($errors->has('country'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('country') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('start_date') ? ' has-error' : '' }}">
                            <label for="start_date" class="col-md-4 control-label">Start Date</label>

                            <div class="col-md-6">
                                <input id="start_date" type="date" class="form-control" name="start_date" value="{{ $project->start_date }}" autofocus>

                                @if ($errors->has('start_date'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('start_date') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('original_estimate') ? ' has-error' : '' }}">
                            <label for="original_estimate" class="col-md-4 control-label">Original Estimate</label>

                            <div class="col-md-6">
                                <input id="original_estimate" type="date" class="form-control" name="original_estimate" value="{{ $project->original_estimate }}" autofocus>

                                @if ($errors->has('original_estimate'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('original_estimate') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('current_estimate') ? ' has-error' : '' }}">
                            <label for="current_estimate" class="col-md-4 control-label">Current Estimate</label>

                            <div class="col-md-6">
                                <input id="current_estimate" type="date" class="form-control" name="current_estimate" value="{{ $project->current_estimate }}" autofocus>

                                @if ($errors->has('current_estimate'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('current_estimate') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('status') ? ' has-error' : '' }}">
                            <label for="status" class="col-md-4 control-label">Status</label>

                            <div class="col-md-6">
                                <input id="status" type="text" class="form-control" name="status" value="{{ $project->status }}" autofocus>

                                @if ($errors->has('status'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('status') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Edit Project
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection