routes/web.php
<?php 

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth']], function() {

Route::get('/', 'PagesController@index');
Route::get('/project', 'PagesController@projects');
Route::get('/tasks', 'PagesController@tasks');
Route::get('/system-page', 'PagesController@system');
Route::get('/proj-config', 'PagesController@projectconfiguration');
Route::get('/add-procurement', 'PagesController@addprocurement');
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::get('/my-profile', 'UserController@profile');
Route::get('/my-profile/{user}',  ['as' => 'users.edit', 'uses' => 'UserController@edit']);
Route::patch('/my-profile/{user}/update',  ['as' => 'users.update', 'uses' => 'UserController@update']);
Route::post('/my-profile', 'UserController@update_avatar');

/* Sytem Config Routes */
Route::group(['middleware' => 'is.admin'], function () {
Route::post('/system', ['as' => 'system.users.store', 'uses' => 'SystemController@store_users']);
Route::get('/system', ['as' => 'system.users.index', 'uses' => 'SystemController@index_users']);
Route::get('/system/users/create', ['as' => 'system.users.create', 'uses' => 'SystemController@create_users']);
Route::delete('/system/users/{user} ', ['as' => 'system.users.destroy', 'uses' => 'SystemController@destroy_users']);
Route::patch('/system/users/{user}', ['as' => 'system.users.update', 'uses' => 'SystemController@update_users']);
Route::get('/system/users/{user}/edit', ['as' => 'system.users.edit', 'uses' => 'SystemController@edit_users']);
});

/* Projects and Tasks Routes */
Route::model('tasks', 'Task');
Route::model('procurements', 'Procurement');
Route::model('elements', 'Element');
Route::model('locations', 'Location');
Route::model('projects', 'Project');

Route::bind('task', function($value, $route) {
	return App\Task::whereSlug($value)->first();
});
Route::bind('project', function($value, $route) {
	return App\Project::whereSlug($value)->first();
});
Route::resource('projects.procurements', 'ProcurementsController');
Route::resource('projects.locations', 'LocationsController');
Route::resource('projects.elements', 'ElementsController');
Route::resource('/projects', 'ProjectsController');
Route::resource('procurements.tasks', 'TasksController');



});


Auth::routes();

app/Task.php
<?php

namespace App;

use Illuminate\Http\Request;
use App\Element;
use App\Procurement;
use App\Project;
use App\Location;
use Illuminate\Database\Eloquent\Model;


class Task extends Model
{
	protected $table = 'tasks';

	protected $guarded = [];


    public function procurement()
	{
		return $this->belongsTo(Procurement::class);
	}
	public function project()
	{
		return $this->belongsTo(Project::class);
	}
}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;

use App\Procurement;
use App\Project;
use App\Location;
use App\Task;
use Illuminate\Support\Facades\Input;
use Redirect;
use App\Http\Controllers\Controller;
use Illuminate\Database\Eloquent\Model;

use Illuminate\Http\Request;

class TasksController extends Controller
{
    public function index(Procurement $procurement)
	{
		return view('tasks.index', compact('procurement'));
	}

	public function create(Procurement $procurement)
	{
		return view('tasks.create', compact('procurement'));
	}

	public function store(Project $project, Procurement $procurement)
	{
		$input = Input::all();
		$input['procurement_id'] = $procurement->id;
		Task::create( $input );
 
		return Redirect::route('projects.show', $project->slug)->with('message', 'Task created.');
	}

	public function show(Procurement $procurement, Project $project, Task $task)
	{
		return view('tasks.show', compact('project','procurement', 'task'));
	}

	public function edit(Procurement $procurement, Task $task)
	{
		return view('tasks.edit', compact('procurement', 'task'));
	}

	public function update(Project $project, Procurement $procurement, Task $task)
	{
		$input = array_except(Input::all(), '_method');
		$task->update($input);

		if (strtotime($task->actual_date) == null) {
			$task->status = null;
		}
		elseif (strtotime($task->actual_date)  > strtotime($task->original_estimate) ) {
			$task->status = 'Overdue';
		}
		elseif (strtotime($task->actual_date)  <= strtotime($task->original_estimate)) {
			$task->status = 'Complete';
		}

		$status = $task->status;
		$task->update(array('status' => $status));
		
 
		return Redirect::route('projects.show', $project->slug)->with('message', 'Task updated.');
	}

	public function destroy(Procurement $procurement, Task $task)
	{
		$task->delete();
 
		return Redirect::route('projects.show', $procurement->id)->with('message', 'Task deleted.');
	}
}

resources/views/tasks/create.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Create Task</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('procurements.tasks.store' , $procurement->id) }}">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                                @if ($errors->has('firstname'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('slug') ? ' has-error' : '' }}">
                            <label for="slug" class="col-md-4 control-label">Slug</label>

                            <div class="col-md-6">
                                <input id="slug" type="text" class="form-control" name="slug" value="{{ old('slug') }}" required autofocus>

                                @if ($errors->has('slug'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('slug') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('catergory') ? ' has-error' : '' }}">
                            <label for="catergory" class="col-md-4 control-label">Catergory</label>

                            <div class="col-md-6">
                                <select name="catergory" class="form-control">
                                    <option value="Design" name="Design" >Design</option>
                                    <option value="Production" name="Production">Production</option>
                                    <option value="Procurement Manager" name="Procurement Manager">Shipping</option>
                                </select>

                                @if ($errors->has('catergory'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('catergory') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('supplier_contact') ? ' has-error' : '' }}">
                            <label for="supplier_contact" class="col-md-4 control-label">Supplier Contact</label>

                            <div class="col-md-6">
                                <input id="supplier_contact" type="text" class="form-control" name="supplier_contact" value="{{ old('project_manager') }}" required autofocus>

                                @if ($errors->has('project_manager'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('project_manager') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

						<div class="form-group{{ $errors->has('start_date') ? ' has-error' : '' }}">
                            <label for="start_date" class="col-md-4 control-label">Start Date</label>

                            <div class="col-md-6">
                                <input id="start_date" type="date" class="form-control" name="start_date" value="{{ old('start_date') }}" autofocus>

                                @if ($errors->has('start_date'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('start_date') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

						<div class="form-group{{ $errors->has('original_estimate') ? ' has-error' : '' }}">
                            <label for="original_estimate" class="col-md-4 control-label">Original Estimate</label>

                            <div class="col-md-6">
                                <input id="original_estimate" type="date" class="form-control" name="original_estimate" value="{{ old('original_estimate') }}" autofocus>

                                @if ($errors->has('original_estimate'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('original_estimate') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>


                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Create Task
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/tasks/edit.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Edit Task</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('procurements.tasks.update', [$procurement->id, $task->slug]) }}">
                        {{ csrf_field() }}
                        {{ method_field('patch') }}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ $task->name }}"  autofocus>

                                @if ($errors->has('firstname'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('slug') ? ' has-error' : '' }}">
                            <label for="slug" class="col-md-4 control-label">Slug</label>

                            <div class="col-md-6">
                                <input id="slug" type="text" class="form-control" name="slug" value="{{ $task->slug }}"  autofocus>

                                @if ($errors->has('slug'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('slug') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('catergory') ? ' has-error' : '' }}">
                            <label for="catergory" class="col-md-4 control-label">Catergory</label>

                            <div class="col-md-6">
                                <select name="catergory" class="form-control">
                                    <option value="Design" name="Design" >Design</option>
                                    <option value="Production" name="Production">Production</option>
                                    <option value="Procurement Manager" name="Procurement Manager">Shipping</option>
                                </select>

                                @if ($errors->has('catergory'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('catergory') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('supplier_contact') ? ' has-error' : '' }}">
                            <label for="supplier_contact" class="col-md-4 control-label">Supplier Contact</label>

                            <div class="col-md-6">
                                <input id="project_manager" type="text" class="form-control" name="supplier_contact" value="{{ $task->supplier_contact }}"  autofocus>

                                @if ($errors->has('supplier_contact'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('supplier_contact') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('start_date') ? ' has-error' : '' }}">
                            <label for="start_date" class="col-md-4 control-label">Start Date</label>

                            <div class="col-md-6">
                                <input id="start_date" type="date" class="form-control" name="start_date" value="{{ $task->start_date }}" autofocus>

                                @if ($errors->has('start_date'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('start_date') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('original_estimate') ? ' has-error' : '' }}">
                            <label for="original_estimate" class="col-md-4 control-label">Original Estimate</label>

                            <div class="col-md-6">
                                <input id="original_estimate" type="date" class="form-control" name="original_estimate" value="{{ $task->original_estimate }}" autofocus>

                                @if ($errors->has('original_estimate'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('original_estimate') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('actual_date') ? ' has-error' : '' }}">
                            <label for="actual_date" class="col-md-4 control-label">Actual Date</label>

                            <div class="col-md-6">
                                <input id="actual_date" type="date" class="form-control" name="actual_date" value="{{ $task->actual_date }}" autofocus>

                                @if ($errors->has('actual_date'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('actual_date') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>


                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Edit Task
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/tasks/index.blade.php
@extends('layouts.app')

@section('content')
	
@endsection

resources/views/tasks/show.blade.php
@extends('layouts.app')
@section('content')
    <h2>
        {!! link_to_route('projects.show', $project->name, [$project->slug]) !!} -
        {{ $task->name }}
    </h2>
 
    {{ $task->description }}
@endsection